version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no circleci@team12.dev.softwareengineeringii.com "./deploy_frontend.sh"
